version: '3.5'
services:
  q_postgres:
    image: postgres:12.0-alpine
    container_name: q_db
    environment:
      - POSTGRES_DB=q_rest
      - POSTGRES_USER=q_rest
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - q_postgres:/var/lib/db
    networks:
      q-drf-net:
        aliases:
          - q_postgres
  backend:
    container_name: q_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend.env
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/backend
    networks:
      q-drf-net:
    depends_on:
      - q_postgres

volumes:
  q_postgres:

networks:
  q-drf-net: